defaults: &defaults
  working_directory: ~/huha
  docker:
    - image: circleci/node:lts
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo npm install -g gulp-cli
            npm install
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  publish:
    <<: *defaults
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - attach_workspace:
          at: .
      - run:
          name: Publish package
          command: npm publish --access=public
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: sudo npm install -g gh-release
      - run:
          name: Publish Release on GitHub
          command: gh-release -y
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deploy:
    working_directory: ~/huha
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET} --delete --cache-control "max-age=31536000, public"

workflows:
  version: 2
  build-test-publish-release-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
            - publish
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - release
          filters:
            branches:
              only: master